RABEL_HOST_NAME: 'example.com'
RABEL_SYSTEM_EMAIL: 'hello@example.com'
SECRET_TOKEN: '8b2653a640acb9b60a996987610684cc789d480a20a6465fd876d879c66f3a3d620afb6fe649d062723a9f09e4aea40445c416a45a63411789e365e31bc71e3d'
RABEL_UPYUN_SWITCH: 'off'
RABEL_UPYUN_OP_NAME: 'example'
RABEL_UPYUN_OP_PASSWORD: 'example'
RABEL_UPYUN_BUCKET: 'example'
RABEL_UPYUN_BUCKET_DOMAIN: 'example.b0.upaiyun.com'
